"""etl models and prompt_items

Revision ID: f9f9c63775fc
Revises: 66bec070d8fc
Create Date: 2026-06-22 00:19:34.455199
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f9f9c63775fc'
down_revision = '66bec070d8fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_datasets',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('format', sa.Enum('csv', 'xlsx', 'json', name='import_format', create_type=False), nullable=False),
    sa.Column('total_questions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String(length=5)), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_etl_datasets_slug')
    )
    op.create_table('chapter_domain_mappings',
    sa.Column('dataset_slug', sa.String(length=100), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=True),
    sa.Column('chapter_title', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['exam_domains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_slug', 'chapter_number', name='uq_cdm_dataset_chapter')
    )
    op.create_table('etl_runs',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.Enum('preview', 'committed', 'rolled_back', name='etl_run_phase'), nullable=False),
    sa.Column('preview_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['etl_datasets.id'], ),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_external_keys',
    sa.Column('dataset_slug', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_slug', 'external_id', 'language', name='uq_qek_dataset_ext_lang')
    )
    op.add_column('questions', sa.Column('prompt_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'prompt_items')
    op.drop_table('question_external_keys')
    op.drop_table('etl_runs')
    op.drop_table('chapter_domain_mappings')
    op.drop_table('etl_datasets')
    # Drop the etl_run_phase enum type explicitly (autogen does not handle this).
    # Do NOT drop import_format — it is shared with import_jobs.
    etl_run_phase = sa.Enum(name='etl_run_phase')
    etl_run_phase.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
